In [ ]:
#Slicing 2D array

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

#Row1 = 0, Row 2 = 1. Thus in row1, slicing takes place

In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
element=arr[1,2]#row,column, starting form 0.after row=1,only elements of row1 are checked.
print(element)

6


In [2]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_slice = arr[0:2, :] #[row sliced(row 0 and 1 sliced from rest of the array), column sliced(: means all columns)]
print(row_slice)


[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
col_slice = arr[:, 1:3]
print(col_slice)

[[2 3]
 [5 6]
 [8 9]]
